language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
before_script:
- npm install
- npm install -g polymer-cli
script: xvfb-run polymer test --npm --module-resolution=node
